import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Container } from "@chakra-ui/react";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sankalan Dasgupta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container
            maxW="100vw"
            minW={"270px"}
            bg="transparent"
            centerContent
            minH={"100vh"}
            padding={{
              base: "2.5em 1.25em 2.5em 1.25em",
              md: "5em 2.5em 5em 2.5em",
              lg: "5em 2.5em 5em 2.5em",
            }}
          >
            <Header>{children}</Header>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
